# Use Python 3.11 slim image as base
FROM python:3.11-slim

# Set working directory
WORKDIR /home

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    ffmpeg \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install flask pandas

# Copy requirements file
COPY requirements.txt .

EXPOSE 5000

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

#    pip install git+https://github.com/openai/whisper.git